name: Build Mobile Apps

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  # Android Build Job
  build-android:
    name: Build Android APK
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.7'
          channel: 'stable'
          cache: true
      
      - name: Get dependencies
        run: flutter pub get
      
      - name: Run analyzer
        run: flutter analyze
      
      - name: Run tests
        run: flutter test
        continue-on-error: true  # 目前可能没有测试
      
      - name: Build Android Debug APK
        run: |
          cd android
          chmod +x ./gradlew
          ./gradlew assembleDebug --no-daemon --stacktrace
        env:
          GRADLE_OPTS: -Xmx4g -Dorg.gradle.daemon=false
      
      - name: Build Android Release APK
        run: |
          cd android
          ./gradlew assembleRelease --no-daemon --stacktrace
        env:
          GRADLE_OPTS: -Xmx4g -Dorg.gradle.daemon=false
      
      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: android-debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
          retention-days: 30
      
      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: android-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 90

  # iOS Build Job
  build-ios:
    name: Build iOS IPA
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.7'
          channel: 'stable'
          cache: true
      
      - name: Get dependencies
        run: flutter pub get
      
      - name: Run analyzer
        run: flutter analyze
      
      - name: Run tests
        run: flutter test
        continue-on-error: true
      
      - name: Build iOS (No Codesign)
        run: flutter build ios --release --no-codesign
      
      - name: Create IPA
        run: |
          cd build/ios/iphoneos
          mkdir Payload
          cp -r Runner.app Payload/
          zip -r app-release.ipa Payload
      
      - name: Upload iOS IPA
        uses: actions/upload-artifact@v4
        with:
          name: ios-release-ipa
          path: build/ios/iphoneos/app-release.ipa
          retention-days: 90

  # 代码质量检查
  code-quality:
    name: Code Quality Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.7'
          channel: 'stable'
          cache: true
      
      - name: Get dependencies
        run: flutter pub get
      
      - name: Check formatting
        run: dart format --set-exit-if-changed .
        continue-on-error: true
      
      - name: Analyze code
        run: flutter analyze
      
      - name: Run tests with coverage
        run: flutter test --coverage
        continue-on-error: true
